version: "3"
services:
  frontend:
    build:
      context: frontend
    container_name: credit_score_frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    build:
      context: .
    container_name: credit_score_backend
    ports:
      - "8080:8080"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge